name: Build and Deploy to Optimizely DXP

env:
  BUILD_PATH: ${{ github.workspace }}/build
  USE_PUBLISH: true

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Gulp and dependencies
        working-directory: src/Foundation/wwwroot/scss
        run: |
          npm install --no-save gulp gulp-sass sass sass-glob

      - name: Create Gulpfile for SCSS compilation
        working-directory: src/Foundation/wwwroot/scss
        run: |
          echo "const gulp = require('gulp');" > gulpfile.js
          echo "const sass = require('gulp-sass')(require('sass'));" >> gulpfile.js
          echo "const sassGlob = require('sass-glob');" >> gulpfile.js
          echo "" >> gulpfile.js
          echo "gulp.task('sass', function () {" >> gulpfile.js
          echo "  return gulp.src('main.scss')" >> gulpfile.js
          echo "    .pipe(sassGlob())" >> gulpfile.js
          echo "    .pipe(sass({ outputStyle: 'compressed' }).on('error', sass.logError))" >> gulpfile.js
          echo "    .pipe(gulp.dest('../css'));" >> gulpfile.js
          echo "});" >> gulpfile.js
          echo "" >> gulpfile.js
          echo "gulp.task('default', gulp.series('sass'));" >> gulpfile.js

      - name: Run Gulp to compile SCSS
        working-directory: src/Foundation/wwwroot/scss
        run: npx gulp

      - name: Write MSBuild override to exclude duplicate module.config
        shell: pwsh
        run: |
          @"
          <Project>
            <ItemGroup>
              <Content Remove="modules\_protected\Geta.NotFoundHandler.Optimizely\module.config" />
            </ItemGroup>
          </Project>
          "@ | Out-File -FilePath "${{ github.workspace }}\ExcludeGetaConfig.targets" -Encoding utf8

      - name: Publish project
        if: env.USE_PUBLISH == 'true'
        shell: pwsh
        run: |
          $overridePath = Join-Path "${{ github.workspace }}" "ExcludeGetaConfig.targets"
          dotnet publish src/Foundation/Foundation.csproj `
            --configuration Release `
            --output "${{ env.BUILD_PATH }}" `
            /p:CustomAfterMicrosoftCommonTargets=$overridePath

      - name: Zip the published output
        shell: pwsh
        run: |
          $timestamp = Get-Date -Format "yyyyMMddHHmmss"
          $zipName = "foundation.cms.app.$timestamp.zip"
          Compress-Archive -Path "${{ env.BUILD_PATH }}\*" -DestinationPath $zipName
          echo "ZIP_NAME=$zipName" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: foundation-cms-zip
          path: ${{ env.ZIP_NAME }}
