name: Build and Package Site

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    env:
      DOTNET_VERSION: 6.0.x
      BUILD_PATH: build
      ARTIFACT_NAME: foundation.cms.app
      USE_PUBLISH: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node-sass + glob importer
        run: |
          npm install node-sass node-sass-glob-importer bootstrap

      - name: Patch SCSS imports to remove ~
        run: |
          Get-ChildItem -Path src/Foundation/wwwroot/scss -Recurse -Include *.scss | ForEach-Object {
            (Get-Content $_.FullName) -replace '~', '' | Set-Content $_.FullName
          }

      - name: Compile SCSS using node-sass with glob support
        run: |
          npx node-sass src/Foundation/wwwroot/scss/main.scss `
            --output src/Foundation/wwwroot/css `
            --output-style compressed `
            --importer node_modules/node-sass-glob-importer/dist/cli.js `
            --include-path node_modules

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Write MSBuild override to exclude duplicate module.config
        run: |
          $content = @"
          <Project>
            <Target Name='RemoveDuplicateGetaConfig' BeforeTargets='AssignTargetPaths'>
              <ItemGroup>
                <Content Remove='@(Content)' Condition=""'%(RelativeDir)%(Filename)%(Extension)' == 'modules\_protected\Geta.NotFoundHandler.Optimizely\module.config'"" />
              </ItemGroup>
            </Target>
          </Project>
          "@
          $content | Set-Content -Path "ExcludeGetaConfig.targets"

      - name: Publish project (Optional)
        if: env.USE_PUBLISH == 'true'
        run: |
          $overridePath = Join-Path "${{ github.workspace }}" "ExcludeGetaConfig.targets"
          dotnet publish src/Foundation/Foundation.csproj `
            --configuration Release `
            --output ${{ env.BUILD_PATH }} `
            /p:CustomAfterMicrosoftCommonTargets=$overridePath

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.BUILD_PATH }}
