name: Build and Deploy to Optimizely DXP

on:
  push:
    branches:
      - main
      - staging

env:
  DOTNET_VERSION: 6.0.x
  BUILD_PATH: build
  ARTIFACT_NAME: foundation.cms.app
  USE_PUBLISH: true  # Change to 'false' to use build instead of publish

jobs:
  build:
    name: Build .NET Solution
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore NuGet packages
        run: dotnet restore Foundation.sln
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node Dependencies
        run: npm install
        shell: pwsh

      - name: Build Frontend Assets using Webpack
        run: npm run prod
        shell: pwsh

      - name: Build or Publish Solution
        run: |
          if ($env:USE_PUBLISH -eq 'true') {
            echo "Running dotnet publish..."
            dotnet publish Foundation.sln --configuration Release --output "${{ env.BUILD_PATH }}"
          } else {
            echo "Running dotnet build..."
            dotnet build Foundation.sln --configuration Release --output "${{ env.BUILD_PATH }}"
          }
        shell: pwsh

      - name: Confirm Build Output Contents
        run: |
          echo "Contents of '${{ env.BUILD_PATH }}':"
          Get-ChildItem -Path "${{ env.BUILD_PATH }}" -Recurse | Select-Object FullName, Length
        shell: pwsh

      - name: Create ZIP
        run: |
          $date = Get-Date -Format "yyyyMMddHHmmss"
          $zipName = "${{ env.ARTIFACT_NAME }}.$date.zip"
          Compress-Archive -Path "${{ env.BUILD_PATH }}\*" -DestinationPath $zipName
          echo "ZIP_NAME=$zipName" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-zip
          path: foundation.cms.app.*.zip
