name: Build and Deploy to Optimizely DXP

env:
  BUILD_PATH: ${{ github.workspace }}/build
  USE_PUBLISH: true

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install SCSS dependencies
        run: |
          cd src/Foundation/wwwroot/scss
          npm init -y
          npm install node-sass node-sass-glob-importer

      - name: Create SCSS compile script
        run: |
          cd src/Foundation/wwwroot/scss
          echo "const sass = require('node-sass');" > compile.js
          echo "const globImporter = require('node-sass-glob-importer');" >> compile.js
          echo "sass.render({" >> compile.js
          echo "  file: 'main.scss'," >> compile.js
          echo "  importer: globImporter()," >> compile.js
          echo "  outputStyle: 'compressed'," >> compile.js
          echo "}, function(error, result) {" >> compile.js
          echo "  if (!error) {" >> compile.js
          echo "    const fs = require('fs');" >> compile.js
          echo "    fs.writeFileSync('../css/main.min.css', result.css);" >> compile.js
          echo "  } else { console.error(error); process.exit(1); }" >> compile.js
          echo "});" >> compile.js

      - name: Compile SCSS with glob support
        run: |
          cd src/Foundation/wwwroot/scss
          node compile.js

      - name: Write MSBuild override to exclude duplicate module.config
        shell: pwsh
        run: |
          @"
          <Project>
            <ItemGroup>
              <Content Remove=\"modules\_protected\Geta.NotFoundHandler.Optimizely\module.config\" />
            </ItemGroup>
          </Project>
          "@ | Out-File -FilePath "${{ github.workspace }}\ExcludeGetaConfig.targets" -Encoding utf8

      - name: Publish project
        if: env.USE_PUBLISH == 'true'
        shell: pwsh
        run: |
          $overridePath = Join-Path "${{ github.workspace }}" "ExcludeGetaConfig.targets"
          dotnet publish src/Foundation/Foundation.csproj `
            --configuration Release `
            --output "${{ env.BUILD_PATH }}" `
            /p:CustomAfterMicrosoftCommonTargets=$overridePath

      - name: Zip the published output
        shell: pwsh
        run: |
          $timestamp = Get-Date -Format "yyyyMMddHHmmss"
          $zipName = "foundation.cms.app.$timestamp.zip"
          Compress-Archive -Path "${{ env.BUILD_PATH }}\*" -DestinationPath $zipName
          echo "ZIP_NAME=$zipName" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: foundation-cms-zip
          path: ${{ env.ZIP_NAME }}
