name: Build and Deploy to Optimizely DXP

on:
  workflow_dispatch:

env:
  ARTIFACT_NAME: foundation.cms.app.${{ github.run_id }}
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: windows-latest
    outputs:
      zip_name: ${{ steps.set-zip-name.outputs.zip_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build Foundation.sln --configuration Release /p:EnableDefaultContentItems=false

      - name: Publish app
        run: dotnet publish Foundation.sln -c Release -o ${{ env.ARTIFACT_NAME }} /p:EnableDefaultContentItems=false /p:ExcludeContentFiles=true

      - name: Create ZIP
        id: set-zip-name
        run: |
          $date = Get-Date -Format "yyyyMMdd"
          $zipName = "foundation.cms.app.$date.zip"
          Compress-Archive -Path "${{ env.ARTIFACT_NAME }}\*" -DestinationPath $zipName
          echo "zip_name=$zipName" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-zip-name.outputs.zip_name }}
          path: ${{ steps.set-zip-name.outputs.zip_name }}

  deploy:
    needs: build
    runs-on: windows-latest
    env:
      ZIP_NAME: ${{ needs.build.outputs.zip_name }}
    steps:
      - name: Download ZIP artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: .

      - name: Set PowerShell Execution Policy
        run: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
        shell: pwsh

      - name: Install EPiCloud PowerShell Module
        run: Install-Module -Name EPiCloud -Force -Scope CurrentUser -AllowClobber
        shell: pwsh

      - name: Deploy ZIP to Optimizely DXP
        run: |
          $clientKey = 'cHa5uGqiIBDGmIEtCycecyrZxktsUCNM0vjDqkk2vUrCLDtW'
          $clientSecret = 'NDm5kxcQ3dY4E1r3XEf7WDdK+ZOGZtcnxEpu0yoPsTu+Qtw1gWxqgcFpLLMwd45c'
          $projectId = '9e999a9a-6dac-47dc-9232-b2ed008f83ca'

          Connect-EpiCloud -ClientKey $clientKey -ClientSecret $clientSecret -ProjectId $projectId

          $zipName = $env:ZIP_NAME
          if (-not (Test-Path -Path $zipName)) {
            Write-Error "ZIP file not found: $zipName"
            exit 1
          }

          Write-Host "Uploading $zipName"
          $sasUri = Get-EpiDeploymentPackageLocation -ProjectId $projectId
          Invoke-RestMethod -Uri $sasUri -Method PUT -InFile $zipName -Headers @{ "x-ms-blob-type" = "BlockBlob" }

          $deployment = Start-EpiDeployment -DeploymentPackage $zipName -TargetEnvironment Integration -DirectDeploy
          $deploymentId = $deployment.Id
          Write-Host "Deployment started with ID: $deploymentId"

          # Poll for deployment completion
          do {
            Start-Sleep -Seconds 30
            $current = Get-EpiDeployment -Id $deploymentId
            $status = $current.Status
            Write-Host "Deployment Status: $status"
          } while ($status -ne "Completed" -and $status -ne "Failed")

          if ($status -eq "Completed") {
            Write-Host "Deployment succeeded!"
          } else {
            Write-Error "Deployment failed!"
            exit 1
          }
        shell: pwsh
